version: "3.8"

services:
  redis:
    container_name: gandalf
    image: redis:latest
    ports:
      - 6379:6379
  url-shortener:
    container_name: frodo
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    links:
      - redis
    depends_on:
      - redis
    environment:
      - db=redis
